include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v17.19.0
  #
stages:
  - register
  - assemble
  - index

Register image:
  stage: register
  extends: .base_register_stage
  variables:
    CONTEXT: . # The folder where the Dockerfile is
    IMAGE_NAME: $CI_REGISTRY_IMAGE # The image name

Download and assemble CSV data:
  stage: assemble
  image: $CI_REGISTRY_IMAGE-assembly:$CI_COMMIT_SHA
  script:
    - bash ./scripts/download_data.sh
  artifacts:
    paths:
      - data/
    expire_in: 4 hour

Run Elastic indexation:
  stage: index
  artifacts:
    paths:
      - data/
    expire_in: 4 hour
  script:
    - yarn install
    - yarn build
    - node dist/index.js
