name: Assembly
on:
  workflow_dispatch:
jobs:
  Assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Fetch data 🌍
        run: |
          export DATA_DIR="./data"
          export OUTPUT_DIR="./output"
          mkdir $DATA_DIR || true
          mkdir $OUTPUT_DIR || true
          ./assembly/scripts/get-data.sh
          echo "--"
          ls $DATA_DIR
          echo "--"
          ls
          echo "--"
          ./assembly/scripts/assemble.sh
          echo "--"
          ls $DATA_DIR
          echo "--"
          ls $OUTPUT_DIR
          echo "--"
          ls -la
          tar -czvf $OUTPUT_DIR/assembly.tgz $OUTPUT_DIR/assembly.csv
          ls -la
